### ISSUE TITLE
Does not work with Node 7

### ISSUE THREAD

**Issue by hongfei** [joychester/Clip#1]
HongfeideMacBook-Pro:Clip hongfei$ node -v
v7.7.3
HongfeideMacBook-Pro:Clip hongfei$ node nightmare_test.js 
Start the Test: 1489976495302
Start to clip: 1489976497043
Target folder created...
PARENT got message: { bucket: '/Users/hongfei/Workspace/prigit/Clip/screenshots_1489976498471/' }
Taking Screenshot No.1
Taking Screenshot No.2
Taking Screenshot No.3
Taking Screenshot No.4
saving bmp image:1
saving bmp image:2
saving bmp image:3
saving bmp image:4
All bmp files saved.
Start imgDiff process: 1489976500605
**(node:65678) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'deasync'**
(node:65678) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:65678) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: path must be a string or Buffer
end of the test: 1489976500918
imgDiff got message from Parent clip Process: { bucket: '/Users/hongfei/Workspace/prigit/Clip/screenshots_1489976498471/',
  loadStart: 1489976497050 }
[]
Start Calculate pixels
(node:65681) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'substr' of undefined
(node:65681) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
png file converted.
png file converted.
png file converted.
png file converted.

**Comment by joychester** [comment]
will fix following then, Thanks!

// waiting for all png files generated
promise.then( function() {
  require('deasync').loopWhile(function(){
    // 'true' will enter the loop;
    // 'false' will exit the loop;
    return (complete.length < imgBufArray.length);
  });
});

**Comment by joychester** [comment]
it is fixed by adding 'deasync' module in package.json and 'deasync' module should be supported by node7 according to https://github.com/abbr/deasync/issues/73

**Comment by joychester** [comment]
#https://github.com/joychester/Clip/commit/0bcc025f08ec363f5bd5d5be553bc829f53a34ce
